name: Scala CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install sbt
      uses: coursier/setup-action@v1
      with:
        apps: sbt

    - name: Compile
      run: sbt compile

    - name: Run tests
      run: sbt test

    - name: Run coverage and send to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        export CI_BRANCH="${GITHUB_REF#refs/heads/}"
        sbt clean coverage test coverageReport coveralls
